openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/tags/:
    get:
      operationId: listTags
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
          description: ''
      tags:
        - api
    post:
      operationId: createTag
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tag'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
      tags:
        - api
  /api/tags/{id}/:
    get:
      operationId: retrieveTag
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this tag.
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
      tags:
        - api
    put:
      operationId: updateTag
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this tag.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tag'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
      tags:
        - api
    patch:
      operationId: partialUpdateTag
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this tag.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tag'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tag'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
      tags:
        - api
    delete:
      operationId: destroyTag
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this tag.
          schema:
            type: string
      responses:
        '204':
          description: ''
      tags:
        - api
  /api/reminder/:
    get:
      operationId: listReminders
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reminder'
          description: ''
      tags:
        - api
    post:
      operationId: createReminder
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reminder'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Reminder'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Reminder'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reminder'
          description: ''
      tags:
        - api
  /api/reminder/{key}/:
    get:
      operationId: retrieveReminder
      description: ''
      parameters:
        - name: key
          in: path
          required: true
          description: A unique value identifying this reminder.
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reminder'
          description: ''
      tags:
        - api
    put:
      operationId: updateReminder
      description: ''
      parameters:
        - name: key
          in: path
          required: true
          description: A unique value identifying this reminder.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reminder'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Reminder'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Reminder'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reminder'
          description: ''
      tags:
        - api
    patch:
      operationId: partialUpdateReminder
      description: ''
      parameters:
        - name: key
          in: path
          required: true
          description: A unique value identifying this reminder.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reminder'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Reminder'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Reminder'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reminder'
          description: ''
      tags:
        - api
    delete:
      operationId: destroyReminder
      description: ''
      parameters:
        - name: key
          in: path
          required: true
          description: A unique value identifying this reminder.
          schema:
            type: string
      responses:
        '204':
          description: ''
      tags:
        - api
  /api/task/:
    get:
      operationId: listTasks
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
          description: ''
      tags:
        - api
    post:
      operationId: createTask
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Task'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
          description: ''
      tags:
        - api
  /api/task/{id}/:
    get:
      operationId: retrieveTask
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique value identifying this task.
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
          description: ''
      tags:
        - api
    put:
      operationId: updateTask
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique value identifying this task.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Task'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
          description: ''
      tags:
        - api
    patch:
      operationId: partialUpdateTask
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique value identifying this task.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Task'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
          description: ''
      tags:
        - api
    delete:
      operationId: destroyTask
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique value identifying this task.
          schema:
            type: string
      responses:
        '204':
          description: ''
      tags:
        - api
components:
  schemas:
    Tag:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        priority:
          type: integer
          maximum: 100
          minimum: 1
        name:
          type: string
          maxLength: 25
        color:
          type: string
          pattern: ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$
          maxLength: 18
      required:
        - name
    Reminder:
      type: object
      properties:
        key:
          type: string
          maxLength: 25
        message:
          type: string
          maxLength: 100
        time:
          type: string
          format: date-time
        color:
          type: string
          pattern: ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$
          maxLength: 18
        added:
          type: string
          format: date-time
          readOnly: true
        updated:
          type: string
          format: date-time
          readOnly: true
      required:
        - key
        - message
        - time
    Task:
      type: object
      properties:
        id:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        title:
          type: string
          maxLength: 100
        description:
          type: string
        duration:
          type: integer
          maximum: 10000
          minimum: 1
        deadline:
          type: string
          format: date-time
          nullable: true
        is_completed:
          type: boolean
        managed_by:
          type: integer
        tags:
          type: integer
          nullable: true
      required:
        - id
        - title
        - managed_by
